<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>XPScript.UI.Browser</AssemblyName>
    <RootNamespace>XPScript.UI.Browser</RootNamespace>
  </PropertyGroup>
</Project>
