using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;

namespace XPScript.Compiler;

internal static class ThirdPartyLicenseNoticeGenerator
{
    public const string OutputFileName = "Third-party-license.txt";

    public static string Generate(string workspace, bool includeDotNetRuntime)
    {
        var builder = new StringBuilder();
        AppendXPScriptLicense(builder);
        AppendNuGetLicenses(builder, workspace);
        if (includeDotNetRuntime)
            AppendDotNetRuntimeNotices(builder);
        return builder.ToString().TrimEnd() + Environment.NewLine;
    }

    public static void PublishSidecar(string generatedNoticePath, string outputExecutablePath)
    {
        var outputDirectory = Path.GetFullPath(Path.GetDirectoryName(Path.GetFullPath(outputExecutablePath)) ?? Environment.CurrentDirectory);
        var target = Path.Combine(outputDirectory, OutputFileName);
        if (Directory.Exists(target))
            throw new CompilerException("Third-party license output path identifies a directory.");

        if (File.Exists(target))
        {
            var info = new FileInfo(target);
            if (info.LinkTarget is not null || (info.Attributes & FileAttributes.ReparsePoint) != 0)
                throw new CompilerException("Third-party license output may not replace a linked file.");
        }

        var staged = Path.Combine(outputDirectory, ".xpscript-license-" + Guid.NewGuid().ToString("N") + ".tmp");
        var backup = Path.Combine(outputDirectory, ".xpscript-license-" + Guid.NewGuid().ToString("N") + ".bak");
        try
        {
            CompilerSecureFileCopy.CopyValidatedRegularFile(generatedNoticePath, staged, "Third-party license notice");
            CompilerPathSecurity.HardenTemporaryFile(staged);
            var hadExisting = File.Exists(target);
            if (hadExisting) File.Move(target, backup);
            try
            {
                File.Move(staged, target);
                if (hadExisting && File.Exists(backup)) File.Delete(backup);
            }
            catch
            {
                if (File.Exists(target)) File.Delete(target);
                if (hadExisting && File.Exists(backup)) File.Move(backup, target);
                throw;
            }
        }
        finally
        {
            try { if (File.Exists(staged)) File.Delete(staged); } catch { }
            try { if (File.Exists(backup)) File.Delete(backup); } catch { }
        }
    }

    private static void AppendXPScriptLicense(StringBuilder builder)
    {
        builder.AppendLine("XPSCRIPT AND THIRD-PARTY LICENSE NOTICES");
        builder.AppendLine("==========================================");
        builder.AppendLine();
        builder.AppendLine("This file is generated by the XPScript compiler for the components used by this application.");
        builder.AppendLine();
        builder.AppendLine("XPScript - Apache License 2.0 redistribution requirements");
        builder.AppendLine("-----------------------------------------------------------");
        builder.AppendLine("XPScript runtime/compiler-derived components included in the generated application are licensed under Apache License 2.0.");
        builder.AppendLine("When redistributing the generated application, keep this license text and all applicable copyright, patent, trademark, attribution and NOTICE information.");
        builder.AppendLine("Modified XPScript-derived source files, when distributed in source form, must carry prominent notices stating that they were changed.");
        builder.AppendLine("The Apache License does not grant trademark rights except for reasonable identification and reproduction of required NOTICE content.");
        builder.AppendLine();
        builder.AppendLine(ReadEmbeddedText("XPScript.LICENSE", "Apache License 2.0 text is unavailable in this compiler build."));

        var notice = ReadEmbeddedText("XPScript.NOTICE", string.Empty);
        if (!string.IsNullOrWhiteSpace(notice))
        {
            builder.AppendLine();
            builder.AppendLine("XPScript NOTICE");
            builder.AppendLine("---------------");
            builder.AppendLine(notice.Trim());
        }
    }

    private static void AppendNuGetLicenses(StringBuilder builder, string workspace)
    {
        var assetsPath = Path.Combine(workspace, "obj", "project.assets.json");
        if (!File.Exists(assetsPath)) return;

        using var document = JsonDocument.Parse(File.ReadAllText(assetsPath));
        if (!document.RootElement.TryGetProperty("libraries", out var libraries) || libraries.ValueKind != JsonValueKind.Object)
            return;

        var packageRoots = new List<string>();
        if (document.RootElement.TryGetProperty("packageFolders", out var folders) && folders.ValueKind == JsonValueKind.Object)
        {
            foreach (var folder in folders.EnumerateObject())
            {
                try
                {
                    var full = Path.GetFullPath(folder.Name);
                    if (Directory.Exists(full)) packageRoots.Add(full);
                }
                catch { }
            }
        }

        var packages = new List<(string Id, string Version)>();
        foreach (var library in libraries.EnumerateObject())
        {
            if (!library.Value.TryGetProperty("type", out var type) || !string.Equals(type.GetString(), "package", StringComparison.OrdinalIgnoreCase))
                continue;
            var separator = library.Name.LastIndexOf('/');
            if (separator <= 0 || separator == library.Name.Length - 1) continue;
            packages.Add((library.Name[..separator], library.Name[(separator + 1)..]));
        }

        if (packages.Count == 0) return;

        builder.AppendLine();
        builder.AppendLine("NuGet dependencies used by this application");
        builder.AppendLine("-------------------------------------------");
        builder.AppendLine("The following package licenses/notices were collected from the exact NuGet package graph restored for this application.");

        var emittedContent = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var package in packages.OrderBy(x => x.Id, StringComparer.OrdinalIgnoreCase).ThenBy(x => x.Version, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine();
            builder.AppendLine($"[{package.Id} {package.Version}]");
            var packageDirectory = FindPackageDirectory(packageRoots, package.Id, package.Version);
            if (packageDirectory is null)
            {
                builder.AppendLine("License metadata could not be read from the restored package cache.");
                continue;
            }

            var license = ReadPackageLicense(packageDirectory, package.Id);
            if (!string.IsNullOrWhiteSpace(license.LicenseExpression))
                builder.AppendLine("License: " + license.LicenseExpression);
            if (!string.IsNullOrWhiteSpace(license.ProjectUrl))
                builder.AppendLine("Project: " + license.ProjectUrl);

            var packageTexts = new List<(string Label, string Text)>();
            if (!string.IsNullOrWhiteSpace(license.LicenseText))
                packageTexts.Add(("License text", license.LicenseText));
            foreach (var notice in ReadPackageNoticeFiles(packageDirectory))
                packageTexts.Add((notice.Label, notice.Text));

            if (packageTexts.Count == 0 && !string.IsNullOrWhiteSpace(license.LicenseExpression))
            {
                var standard = StandardLicenseText(license.LicenseExpression);
                if (!string.IsNullOrWhiteSpace(standard)) packageTexts.Add(("License text", standard));
            }

            if (packageTexts.Count == 0)
            {
                builder.AppendLine("No package-local license text was found; consult the package metadata/project URL before redistribution.");
                continue;
            }

            foreach (var entry in packageTexts)
            {
                var normalized = entry.Text.Trim();
                var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(normalized)));
                if (!emittedContent.Add(hash))
                {
                    builder.AppendLine($"{entry.Label}: same text as an earlier package notice in this file.");
                    continue;
                }
                builder.AppendLine();
                builder.AppendLine(entry.Label + ":");
                builder.AppendLine(normalized);
            }
        }
    }

    private static void AppendDotNetRuntimeNotices(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("Microsoft .NET runtime bundled with this application");
        builder.AppendLine("----------------------------------------------------");
        builder.AppendLine("This application was published self-contained. The .NET runtime is redistributed with the application.");
        builder.AppendLine("The .NET runtime is licensed under the MIT License and contains third-party components with their own notices.");

        var root = ResolveDotNetRoot();
        var license = root is null ? null : FindFirstExisting(root, "LICENSE.txt", "LICENSE.TXT", "license.txt");
        var notices = root is null ? null : FindFirstExisting(root, "ThirdPartyNotices.txt", "THIRD-PARTY-NOTICES.TXT", "ThirdPartyNotices.TXT");

        builder.AppendLine();
        builder.AppendLine(".NET license:");
        builder.AppendLine(license is not null ? File.ReadAllText(license).Trim() : StandardLicenseText("MIT"));

        builder.AppendLine();
        builder.AppendLine(".NET third-party notices:");
        if (notices is not null)
            builder.AppendLine(File.ReadAllText(notices).Trim());
        else
            builder.AppendLine("The SDK installation used for this publish did not expose a readable ThirdPartyNotices file. See https://github.com/dotnet/runtime/blob/main/THIRD-PARTY-NOTICES.TXT for the .NET runtime third-party notices.");
    }

    private static string? ResolveDotNetRoot()
    {
        try
        {
            var host = CompilerToolResolver.ResolveDotnetHost();
            var info = new FileInfo(host);
            if (info.LinkTarget is not null || (info.Attributes & FileAttributes.ReparsePoint) != 0)
                host = info.ResolveLinkTarget(returnFinalTarget: true)?.FullName ?? host;
            var directory = Path.GetDirectoryName(Path.GetFullPath(host));
            if (!string.IsNullOrWhiteSpace(directory) && Directory.Exists(directory)) return directory;
        }
        catch { }
        return null;
    }

    private static string? FindFirstExisting(string directory, params string[] names)
    {
        foreach (var name in names)
        {
            var path = Path.Combine(directory, name);
            if (File.Exists(path)) return path;
        }
        return null;
    }

    private static string? FindPackageDirectory(IEnumerable<string> roots, string id, string version)
    {
        foreach (var root in roots)
        {
            var path = Path.Combine(root, id.ToLowerInvariant(), version.ToLowerInvariant());
            if (Directory.Exists(path)) return path;
        }
        return null;
    }

    private sealed record PackageLicense(string? LicenseExpression, string? LicenseText, string? ProjectUrl);

    private static PackageLicense ReadPackageLicense(string packageDirectory, string packageId)
    {
        try
        {
            var nuspec = Directory.EnumerateFiles(packageDirectory, "*.nuspec", SearchOption.TopDirectoryOnly).FirstOrDefault();
            if (nuspec is null) return new(null, null, null);
            var document = XDocument.Load(nuspec);
            var metadata = document.Descendants().FirstOrDefault(e => e.Name.LocalName == "metadata");
            if (metadata is null) return new(null, null, null);
            var licenseElement = metadata.Elements().FirstOrDefault(e => e.Name.LocalName == "license");
            var projectUrl = metadata.Elements().FirstOrDefault(e => e.Name.LocalName == "projectUrl")?.Value.Trim();
            if (licenseElement is null) return new(null, null, projectUrl);

            var type = licenseElement.Attribute("type")?.Value;
            var value = licenseElement.Value.Trim();
            if (string.Equals(type, "file", StringComparison.OrdinalIgnoreCase))
            {
                var candidate = Path.GetFullPath(Path.Combine(packageDirectory, value.Replace('/', Path.DirectorySeparatorChar)));
                var root = Path.GetFullPath(packageDirectory) + Path.DirectorySeparatorChar;
                if (candidate.StartsWith(root, StringComparison.OrdinalIgnoreCase) && File.Exists(candidate))
                    return new(null, TryReadText(candidate), projectUrl);
                return new(null, null, projectUrl);
            }
            return new(value, null, projectUrl);
        }
        catch
        {
            return new(null, null, null);
        }
    }

    private static IEnumerable<(string Label, string Text)> ReadPackageNoticeFiles(string packageDirectory)
    {
        var candidates = Directory.EnumerateFiles(packageDirectory, "*", SearchOption.TopDirectoryOnly)
            .Where(path =>
            {
                var name = Path.GetFileName(path);
                return name.StartsWith("NOTICE", StringComparison.OrdinalIgnoreCase) ||
                       name.StartsWith("THIRD-PARTY", StringComparison.OrdinalIgnoreCase) ||
                       name.StartsWith("THIRDPARTY", StringComparison.OrdinalIgnoreCase);
            })
            .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase);

        foreach (var path in candidates)
        {
            var text = TryReadText(path);
            if (!string.IsNullOrWhiteSpace(text)) yield return (Path.GetFileName(path), text);
        }
    }

    private static string? TryReadText(string path)
    {
        try
        {
            var info = new FileInfo(path);
            if (info.Length > 2_000_000) return null;
            return File.ReadAllText(path);
        }
        catch { return null; }
    }

    private static string ReadEmbeddedText(string resourceName, string fallback)
    {
        try
        {
            using var stream = typeof(ThirdPartyLicenseNoticeGenerator).Assembly.GetManifestResourceStream(resourceName);
            if (stream is null) return fallback;
            using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
            return reader.ReadToEnd();
        }
        catch { return fallback; }
    }

    private static string StandardLicenseText(string expression)
    {
        if (expression.Equals("MIT", StringComparison.OrdinalIgnoreCase))
            return """
MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
""";
        return string.Empty;
    }
}
