using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace LSLite.Compiler;

public sealed class LotusTranspiler
{
    private static readonly Dictionary<string, string> TypeMap =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["String"] = "string",
            ["Integer"] = "int",
            ["Long"] = "long",
            ["Double"] = "double",
            ["Single"] = "float",
            ["Boolean"] = "bool",
            ["Byte"] = "byte",
            ["Date"] = "DateTime",
            ["Variant"] = "dynamic",
            ["Object"] = "object"
        };

    private static readonly string[] RuntimeFunctions =
    [
        "Len", "Left", "Right", "Mid", "UCase", "LCase", "Trim",
        "LTrim", "RTrim", "CStr", "CInt", "CLng", "CDbl", "CSng",
        "CBool", "Abs", "Int", "Fix", "Round", "Sqr", "Rnd",
        "Now", "Today", "Date", "Time", "Year", "Month", "Day",
        "Hour", "Minute", "Second", "Chr", "Asc", "Instr",
        "Replace", "Space", "String", "IsNumeric", "Val", "Hex",
        "Oct", "Format", "Split", "Join", "InputBox", "MsgBox"
    ];

    private string? _currentFunction;
    private string? _currentFunctionReturnType;
    private readonly Dictionary<string, string> _variableTypes =
        new(StringComparer.OrdinalIgnoreCase);
    private int _indent;

    public string Transpile(string source, string sourceName)
    {
        var normalized = source.Replace("\r\n", "\n").Replace('\r', '\n');
        var lines = normalized.Split('\n');

        var entryPoint = FindEntryPoint(lines);

        var body = new StringBuilder();

        _currentFunction = null;
        _currentFunctionReturnType = null;
        _variableTypes.Clear();
        _indent = 1;

        for (var i = 0; i < lines.Length; i++)
        {
            var original = lines[i];
            var line = StripComment(original).Trim();

            if (string.IsNullOrWhiteSpace(line))
                continue;

            try
            {
                EmitLine(body, line);
            }
            catch (CompilerException ex)
            {
                throw new CompilerException(
                    $"{sourceName}({i + 1}): {ex.Message}" +
                    Environment.NewLine +
                    $"  {original.Trim()}");
            }
        }

        if (_currentFunction is not null)
            throw new CompilerException(
                $"Missing End Function/End Sub for '{_currentFunction}'.");

        return $$"""
// Generated by LS Lite Compiler.
// Source: {{EscapeComment(sourceName)}}
using System;
using System.Globalization;
using System.Linq;

internal static class Program
{
    public static void Main(string[] args)
    {
        {{entryPoint}}();
    }

{{body}}
}

{{LotusRuntimeSource.Code}}
""";
    }

    public string Transpile(string source) => Transpile(source, "input.ls");

    private void EmitLine(StringBuilder sb, string line)
    {
        if (Regex.IsMatch(line, @"^Option\s+(Declare|Public|Private)\b", RegexOptions.IgnoreCase))
            return;

        var subMatch = Regex.Match(line, @"^(?:Public\s+|Private\s+)?Sub\s+([A-Za-z_]\w*)\s*\((.*)\)\s*$", RegexOptions.IgnoreCase);
        if (subMatch.Success)
        {
            EnsureOutsideProcedure("Sub");
            _currentFunction = subMatch.Groups[1].Value;
            _currentFunctionReturnType = null;
            _variableTypes.Clear();
            var args = ParseArguments(subMatch.Groups[2].Value);
            RegisterArguments(subMatch.Groups[2].Value);
            Write(sb, $"public static void {_currentFunction}({args})");
            Write(sb, "{");
            _indent++;
            return;
        }

        var functionMatch = Regex.Match(line, @"^(?:Public\s+|Private\s+)?Function\s+([A-Za-z_]\w*)\s*\((.*)\)\s*(?:As\s+([A-Za-z_]\w*))?\s*$", RegexOptions.IgnoreCase);
        if (functionMatch.Success)
        {
            EnsureOutsideProcedure("Function");
            _currentFunction = functionMatch.Groups[1].Value;
            var typeName = string.IsNullOrWhiteSpace(functionMatch.Groups[3].Value) ? "Variant" : functionMatch.Groups[3].Value;
            _currentFunctionReturnType = MapType(typeName);
            _variableTypes.Clear();
            var args = ParseArguments(functionMatch.Groups[2].Value);
            RegisterArguments(functionMatch.Groups[2].Value);
            Write(sb, $"public static {_currentFunctionReturnType} {_currentFunction}({args})");
            Write(sb, "{");
            _indent++;
            Write(sb, $"{_currentFunctionReturnType} __result = {DefaultValue(_currentFunctionReturnType)};");
            return;
        }

        if (Regex.IsMatch(line, @"^End\s+Sub$", RegexOptions.IgnoreCase))
        {
            if (_currentFunction is null || _currentFunctionReturnType is not null)
                throw new CompilerException("Unexpected End Sub.");
            _indent--;
            Write(sb, "}");
            _currentFunction = null;
            _variableTypes.Clear();
            return;
        }

        if (Regex.IsMatch(line, @"^End\s+Function$", RegexOptions.IgnoreCase))
        {
            if (_currentFunction is null || _currentFunctionReturnType is null)
                throw new CompilerException("Unexpected End Function.");
            Write(sb, "return __result;");
            _indent--;
            Write(sb, "}");
            _currentFunction = null;
            _currentFunctionReturnType = null;
            _variableTypes.Clear();
            return;
        }

        EnsureInsideProcedure();

        var dimMatch = Regex.Match(line, @"^Dim\s+([A-Za-z_]\w*)\s*(?:As\s+([A-Za-z_]\w*))?$", RegexOptions.IgnoreCase);
        if (dimMatch.Success)
        {
            var name = dimMatch.Groups[1].Value;
            var type = MapType(string.IsNullOrWhiteSpace(dimMatch.Groups[2].Value) ? "Variant" : dimMatch.Groups[2].Value);
            _variableTypes[name] = type;
            Write(sb, $"{type} {name} = {DefaultValue(type)};");
            return;
        }

        var ifMatch = Regex.Match(line, @"^If\s+(.+)\s+Then$", RegexOptions.IgnoreCase);
        if (ifMatch.Success)
        {
            Write(sb, $"if ({TransformCondition(ifMatch.Groups[1].Value)})");
            Write(sb, "{");
            _indent++;
            return;
        }

        var elseifMatch = Regex.Match(line, @"^ElseIf\s+(.+)\s+Then$", RegexOptions.IgnoreCase);
        if (elseifMatch.Success)
        {
            _indent--;
            Write(sb, "}");
            Write(sb, $"else if ({TransformCondition(elseifMatch.Groups[1].Value)})");
            Write(sb, "{");
            _indent++;
            return;
        }

        if (Regex.IsMatch(line, @"^Else$", RegexOptions.IgnoreCase))
        {
            _indent--;
            Write(sb, "}");
            Write(sb, "else");
            Write(sb, "{");
            _indent++;
            return;
        }

        if (Regex.IsMatch(line, @"^End\s+If$", RegexOptions.IgnoreCase))
        {
            _indent--;
            Write(sb, "}");
            return;
        }

        var forMatch = Regex.Match(line, @"^For\s+([A-Za-z_]\w*)\s*=\s*(.+?)\s+To\s+(.+?)(?:\s+Step\s+(.+))?$", RegexOptions.IgnoreCase);
        if (forMatch.Success)
        {
            var variable = forMatch.Groups[1].Value;
            var start = TransformExpression(forMatch.Groups[2].Value);
            var end = TransformExpression(forMatch.Groups[3].Value);
            var step = string.IsNullOrWhiteSpace(forMatch.Groups[4].Value) ? "1" : TransformExpression(forMatch.Groups[4].Value);
            Write(sb, $"foreach (var __forValue in LotusRuntime.Range({start}, {end}, {step}))");
            Write(sb, "{");
            _indent++;
            Write(sb, $"{variable} = Convert.ToInt64(__forValue);");
            return;
        }

        if (Regex.IsMatch(line, @"^Next(?:\s+[A-Za-z_]\w*)?$", RegexOptions.IgnoreCase))
        {
            _indent--;
            Write(sb, "}");
            return;
        }

        var whileMatch = Regex.Match(line, @"^While\s+(.+)$", RegexOptions.IgnoreCase);
        if (whileMatch.Success)
        {
            Write(sb, $"while ({TransformCondition(whileMatch.Groups[1].Value)})");
            Write(sb, "{");
            _indent++;
            return;
        }

        if (Regex.IsMatch(line, @"^Wend$", RegexOptions.IgnoreCase))
        {
            _indent--;
            Write(sb, "}");
            return;
        }

        if (Regex.IsMatch(line, @"^Do$", RegexOptions.IgnoreCase))
        {
            Write(sb, "while (true)");
            Write(sb, "{");
            _indent++;
            return;
        }

        var doWhile = Regex.Match(line, @"^Do\s+While\s+(.+)$", RegexOptions.IgnoreCase);
        if (doWhile.Success)
        {
            Write(sb, $"while ({TransformCondition(doWhile.Groups[1].Value)})");
            Write(sb, "{");
            _indent++;
            return;
        }

        var doUntil = Regex.Match(line, @"^Do\s+Until\s+(.+)$", RegexOptions.IgnoreCase);
        if (doUntil.Success)
        {
            Write(sb, $"while (!({TransformCondition(doUntil.Groups[1].Value)}))");
            Write(sb, "{");
            _indent++;
            return;
        }

        if (Regex.IsMatch(line, @"^Loop$", RegexOptions.IgnoreCase))
        {
            _indent--;
            Write(sb, "}");
            return;
        }

        var loopWhile = Regex.Match(line, @"^Loop\s+While\s+(.+)$", RegexOptions.IgnoreCase);
        if (loopWhile.Success)
        {
            Write(sb, $"if (!({TransformCondition(loopWhile.Groups[1].Value)})) break;");
            _indent--;
            Write(sb, "}");
            return;
        }

        var loopUntil = Regex.Match(line, @"^Loop\s+Until\s+(.+)$", RegexOptions.IgnoreCase);
        if (loopUntil.Success)
        {
            Write(sb, $"if ({TransformCondition(loopUntil.Groups[1].Value)}) break;");
            _indent--;
            Write(sb, "}");
            return;
        }

        if (Regex.IsMatch(line, @"^Exit\s+(For|Do|While)$", RegexOptions.IgnoreCase))
        {
            Write(sb, "break;");
            return;
        }

        if (Regex.IsMatch(line, @"^Exit\s+Sub$", RegexOptions.IgnoreCase))
        {
            Write(sb, "return;");
            return;
        }

        if (Regex.IsMatch(line, @"^Exit\s+Function$", RegexOptions.IgnoreCase))
        {
            Write(sb, "return __result;");
            return;
        }

        var returnMatch = Regex.Match(line, @"^Return(?:\s+(.+))?$", RegexOptions.IgnoreCase);
        if (returnMatch.Success)
        {
            Write(sb, string.IsNullOrWhiteSpace(returnMatch.Groups[1].Value) ? "return;" : $"return {TransformExpression(returnMatch.Groups[1].Value)};");
            return;
        }

        var printMatch = Regex.Match(line, @"^Print\s+(.+)$", RegexOptions.IgnoreCase);
        if (printMatch.Success)
        {
            Write(sb, $"Console.WriteLine({TransformExpression(printMatch.Groups[1].Value)});");
            return;
        }

        var callMatch = Regex.Match(line, @"^Call\s+([A-Za-z_]\w*)\s*\((.*)\)$", RegexOptions.IgnoreCase);
        if (callMatch.Success)
        {
            Write(sb, $"{callMatch.Groups[1].Value}({TransformArgumentList(callMatch.Groups[2].Value)});");
            return;
        }

        var assignmentMatch = Regex.Match(line, @"^(?:Let\s+)?([A-Za-z_]\w*)\s*=\s*(.+)$", RegexOptions.IgnoreCase);
        if (assignmentMatch.Success)
        {
            var name = assignmentMatch.Groups[1].Value;
            var expr = TransformExpression(assignmentMatch.Groups[2].Value);
            if (_currentFunctionReturnType is not null && name.Equals(_currentFunction, StringComparison.OrdinalIgnoreCase))
                Write(sb, $"__result = {expr};");
            else
                Write(sb, $"{name} = {expr};");
            return;
        }

        var bareCall = Regex.Match(line, @"^([A-Za-z_]\w*)\s*\((.*)\)$", RegexOptions.IgnoreCase);
        if (bareCall.Success)
        {
            var callName = bareCall.Groups[1].Value;
            var callArgs = TransformArgumentList(bareCall.Groups[2].Value);
            if (RuntimeFunctions.Any(fn => fn.Equals(callName, StringComparison.OrdinalIgnoreCase)))
                Write(sb, $"LotusRuntime.{callName}({callArgs});");
            else
                Write(sb, $"{callName}({callArgs});");
            return;
        }

        throw new CompilerException($"Unsupported statement: {line}");
    }

    private static string FindEntryPoint(string[] lines)
    {
        foreach (var raw in lines)
        {
            var line = StripComment(raw).Trim();
            if (Regex.IsMatch(line, @"^(?:Public\s+|Private\s+)?Sub\s+Main\b", RegexOptions.IgnoreCase))
                return "Main";
        }
        foreach (var raw in lines)
        {
            var line = StripComment(raw).Trim();
            if (Regex.IsMatch(line, @"^(?:Public\s+|Private\s+)?Sub\s+Initialize\b", RegexOptions.IgnoreCase))
                return "Initialize";
        }
        throw new CompilerException("No entry point found. Add Sub Main() or Sub Initialize().");
    }

    private void RegisterArguments(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return;
        foreach (var part in SplitOutsideStrings(raw, ','))
        {
            var match = Regex.Match(part.Trim(), @"^(?:(ByVal|ByRef)\s+)?([A-Za-z_]\w*)\s*(?:As\s+([A-Za-z_]\w*))?$", RegexOptions.IgnoreCase);
            if (!match.Success) continue;
            var name = match.Groups[2].Value;
            var type = MapType(string.IsNullOrWhiteSpace(match.Groups[3].Value) ? "Variant" : match.Groups[3].Value);
            _variableTypes[name] = type;
        }
    }

    private string ParseArguments(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return "";
        var converted = new List<string>();
        foreach (var part in SplitOutsideStrings(raw, ','))
        {
            var match = Regex.Match(part.Trim(), @"^(?:(ByVal|ByRef)\s+)?([A-Za-z_]\w*)\s*(?:As\s+([A-Za-z_]\w*))?$", RegexOptions.IgnoreCase);
            if (!match.Success) throw new CompilerException($"Unsupported argument declaration: {part.Trim()}");
            if (match.Groups[1].Value.Equals("ByRef", StringComparison.OrdinalIgnoreCase))
                throw new CompilerException("ByRef is not supported in this first compiler version.");
            var name = match.Groups[2].Value;
            var type = MapType(string.IsNullOrWhiteSpace(match.Groups[3].Value) ? "Variant" : match.Groups[3].Value);
            converted.Add($"{type} {name}");
        }
        return string.Join(", ", converted);
    }

    private string TransformCondition(string expression)
    {
        var transformed = TransformExpression(expression);
        transformed = Regex.Replace(transformed, @"(?<![<>=!])=(?!=)", "==");
        return transformed;
    }

    private string TransformExpression(string expression)
    {
        var pieces = SplitStringLiterals(expression);
        var result = new StringBuilder();
        foreach (var piece in pieces)
        {
            if (piece.IsString)
            {
                result.Append(ConvertLotusStringLiteral(piece.Text));
                continue;
            }
            var text = piece.Text;
            text = text.Replace("<>", "!=", StringComparison.Ordinal);
            text = Regex.Replace(text, @"\bAnd\b", "&&", RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"\bOr\b", "||", RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"\bNot\b", "!", RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"\bMod\b", "%", RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"\bTrue\b", "true", RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"\bFalse\b", "false", RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"\bNothing\b", "null", RegexOptions.IgnoreCase);
            text = text.Replace("&", "+", StringComparison.Ordinal);
            foreach (var fn in RuntimeFunctions)
            {
                text = Regex.Replace(text, $@"(?<![\w.]){Regex.Escape(fn)}\s*\(", $"LotusRuntime.{fn}(", RegexOptions.IgnoreCase);
            }
            result.Append(text);
        }
        return result.ToString().Trim();
    }

    private string TransformArgumentList(string raw) => string.Join(", ", SplitOutsideStrings(raw, ',').Select(TransformExpression));

    private static string MapType(string lotusType) => TypeMap.TryGetValue(lotusType.Trim(), out var csharpType) ? csharpType : throw new CompilerException($"Unsupported type: {lotusType}");

    private static string DefaultValue(string type) => type switch
    {
        "string" => "\"\"",
        "bool" => "false",
        "DateTime" => "default",
        "dynamic" => "null!",
        "object" => "null!",
        _ => "0"
    };

    private void EnsureOutsideProcedure(string keyword)
    {
        if (_currentFunction is not null) throw new CompilerException($"{keyword} cannot be nested inside another procedure.");
    }

    private void EnsureInsideProcedure()
    {
        if (_currentFunction is null) throw new CompilerException("Executable statements must be inside Sub Main/Initialize or another procedure.");
    }

    private void Write(StringBuilder sb, string text)
    {
        if (_indent < 1) throw new CompilerException("Unexpected block terminator.");
        sb.Append(' ', _indent * 4);
        sb.AppendLine(text);
    }

    private static string StripComment(string line)
    {
        var inString = false;
        for (var i = 0; i < line.Length; i++)
        {
            if (line[i] == '"')
            {
                if (inString && i + 1 < line.Length && line[i + 1] == '"') { i++; continue; }
                inString = !inString;
                continue;
            }
            if (!inString && line[i] == '\'') return line[..i];
        }
        return line;
    }

    private static List<(string Text, bool IsString)> SplitStringLiterals(string expression)
    {
        var result = new List<(string, bool)>();
        var current = new StringBuilder();
        var inString = false;
        for (var i = 0; i < expression.Length; i++)
        {
            var c = expression[i];
            if (c == '"')
            {
                if (inString && i + 1 < expression.Length && expression[i + 1] == '"') { current.Append("\"\""); i++; continue; }
                if (inString) { current.Append(c); result.Add((current.ToString(), true)); current.Clear(); inString = false; }
                else { if (current.Length > 0) { result.Add((current.ToString(), false)); current.Clear(); } current.Append(c); inString = true; }
                continue;
            }
            current.Append(c);
        }
        if (current.Length > 0) result.Add((current.ToString(), inString));
        if (inString) throw new CompilerException("Unterminated string literal.");
        return result;
    }

    private static string ConvertLotusStringLiteral(string literal)
    {
        if (literal.Length < 2 || literal[0] != '"' || literal[^1] != '"') throw new CompilerException("Invalid string literal.");
        var inner = literal[1..^1].Replace("\"\"", "\\\"");
        inner = inner.Replace("\\", "\\\\").Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t");
        inner = inner.Replace("\\\\\"", "\\\"");
        return "\"" + inner + "\"";
    }

    private static List<string> SplitOutsideStrings(string value, char separator)
    {
        var result = new List<string>();
        var current = new StringBuilder();
        var inString = false;
        var parenDepth = 0;
        for (var i = 0; i < value.Length; i++)
        {
            var c = value[i];
            if (c == '"')
            {
                current.Append(c);
                if (inString && i + 1 < value.Length && value[i + 1] == '"') { current.Append(value[++i]); continue; }
                inString = !inString;
                continue;
            }
            if (!inString)
            {
                if (c == '(') parenDepth++;
                if (c == ')') parenDepth--;
                if (c == separator && parenDepth == 0) { result.Add(current.ToString()); current.Clear(); continue; }
            }
            current.Append(c);
        }
        result.Add(current.ToString());
        return result;
    }

    private static string EscapeComment(string value) => value.Replace("\r", " ").Replace("\n", " ");
}
