<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/XPScript.Compiler/XPScript.Compiler.csproj" />
    <ProjectReference Include="../../src/XPScript.UI.Desktop/XPScript.UI.Desktop.csproj" />
  </ItemGroup>
</Project>
