from pathlib import Path

path = Path('todo/runtime-reference-todo.md')
text = path.read_text(encoding='utf-8')
old = '''- [ ] support all valid `If` statement layouts consistently:\n  - [ ] single-line `If condition Then statement`\n  - [ ] `If condition Then` followed by statement(s) and `End If` on a later line\n  - [ ] fully multiline block form with `If`, `Then`, body and `End If` on separate lines\n  - [ ] ensure Date/comparison lowering and other preprocessors preserve single-line `If ... Then ...` syntax instead of producing `Unsupported statement` diagnostics; regression discovered by `examples/date-comparisons.xps` testing\n'''
new = '''- [ ] support all valid `If` statement layouts consistently:\n  - [ ] single-line `If condition Then statement`\n  - [ ] single-line branches such as `If condition Then statement Else statement` and applicable `ElseIf condition Then statement` forms\n  - [ ] `If condition Then` followed by statement(s) and `End If` on a later line\n  - [ ] fully multiline block form with `If`, `Then`, body and `End If` on separate lines\n  - [ ] ensure Date/comparison lowering and other preprocessors preserve single-line `If ... Then ...` syntax instead of producing `Unsupported statement` diagnostics; regression discovered by `examples/date-comparisons.xps` testing\n- [ ] audit all documented control-flow/declaration statement layouts for the same line-shape assumption:\n  - [ ] verify `_` line continuation remains accepted for long expressions, argument lists, procedure headers and control-flow expressions\n  - [ ] verify `ElseIf` / `Else` supported layouts and nested single-line/block combinations\n  - [ ] verify `Select Case`, `Case`, `With`, `For/Next`, `ForAll`, `Do/Loop`, `While/Wend`, procedure/property/class headers and native declarations do not produce false `Unsupported statement` errors for documented/valid multiline layouts\n  - [ ] add regression samples for every newly identified valid alternate layout; do not add arbitrary unsupported grammar forms merely because keywords can physically be split\n'''
if old not in text:
    raise SystemExit('Expected If TODO block not found in restored main file')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
