using System.Globalization;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using YamlDotNet.Core;
using YamlDotNet.RepresentationModel;

namespace XPScript.Web.Compiler;

public sealed record XpsOpenApiGenerationResult(string OpenApiVersion, string Source, IReadOnlyList<string> Operations, IReadOnlyList<string> Models);
public sealed record XpsOpenApiGenerationOptions(IReadOnlySet<string>? IncludedOperations = null);
public sealed class XpsOpenApiGenerationException : Exception { public XpsOpenApiGenerationException(string message) : base(message) { } public XpsOpenApiGenerationException(string message, Exception innerException) : base(message, innerException) { } }

public sealed class XpsOpenApiGenerator
{
    private static readonly string[] HttpMethods = ["get", "post", "put", "patch", "delete", "head", "options", "trace"];
    private static readonly Regex IdentifierPattern = new("^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.CultureInvariant);
    private static readonly HashSet<string> LexicalKeywords = new(StringComparer.OrdinalIgnoreCase) { "Abstract", "And", "As", "Base", "Bool", "Boolean", "Break", "Byte", "ByRef", "ByVal", "Call", "Case", "Catch", "Char", "Checked", "Class", "Const", "Continue", "Date", "Decimal", "Default", "Delegate", "Dim", "Do", "Double", "Each", "Else", "ElseIf", "End", "Enum", "Event", "Exit", "Explicit", "Extern", "False", "Finally", "Fixed", "Float", "For", "Foreach", "Function", "Goto", "If", "Implicit", "In", "Int", "Integer", "Interface", "Internal", "Is", "Lock", "Long", "Loop", "Mod", "Namespace", "New", "Next", "Nothing", "Not", "Null", "Object", "On", "Operator", "Option", "Or", "Out", "Override", "Params", "Private", "Protected", "Public", "Readonly", "Ref", "Return", "Sbyte", "Sealed", "Select", "Set", "Short", "Single", "Sizeof", "Stackalloc", "Static", "Step", "String", "Struct", "Sub", "Switch", "Then", "This", "Throw", "To", "True", "Try", "Typeof", "Uint", "Ulong", "Unchecked", "Unsafe", "Ushort", "Using", "Variant", "Virtual", "Void", "Volatile", "Wend", "While", "With", "Xor" };

    public XpsOpenApiGenerationResult GenerateFile(string specificationPath) { ArgumentException.ThrowIfNullOrWhiteSpace(specificationPath); var fullPath = Path.GetFullPath(specificationPath); if (!File.Exists(fullPath)) throw new FileNotFoundException("OpenAPI specification file was not found.", fullPath); return Generate(File.ReadAllText(fullPath), Path.GetFileName(fullPath)); }
    public XpsOpenApiGenerationResult GenerateFile(string specificationPath, XpsOpenApiGenerationOptions options) { ArgumentException.ThrowIfNullOrWhiteSpace(specificationPath); var fullPath = Path.GetFullPath(specificationPath); if (!File.Exists(fullPath)) throw new FileNotFoundException("OpenAPI specification file was not found.", fullPath); return Generate(File.ReadAllText(fullPath), Path.GetFileName(fullPath), options); }
    public XpsOpenApiGenerationResult Generate(string specification, string? sourceName = null) => Generate(specification, sourceName, null);
    public XpsOpenApiGenerationResult Generate(string specification, string? sourceName, XpsOpenApiGenerationOptions? options) { ArgumentException.ThrowIfNullOrWhiteSpace(specification); XpsOpenApiSchema.ValidateExternalReferences(specification, sourceName); var root = ParseDocument(specification, sourceName); var normalized = XpsOpenApiSchema.NormalizeDocument(root); var version = normalized.Version; using var versionScope = XpsOpenApiSchema.UseOpenApiVersion(version); var modelCatalog = CollectComponentModels(root); var models = modelCatalog.Models; using var typeNameScope = XpsOpenApiSchema.UseReferenceTypeNames(modelCatalog.TypeNames); var operations = CollectOperations(root, models); if (options?.IncludedOperations is { Count: > 0 } included) { var allModels = models; operations = operations.Where(operation => included.Contains(operation.Name) || included.Any(item => IsSelectedOperation(operation.Name, item)) || included.Contains(operation.Method + " " + operation.Path) || included.Contains(operation.Path)).ToList(); models = SelectReferencedModels(root, modelCatalog, included); foreach (var pair in allModels.Where(pair => operations.Any(operation => pair.Key.Equals(operation.Name + "Body", StringComparison.OrdinalIgnoreCase)))) models[pair.Key] = pair.Value; } if (operations.Count == 0) throw new XpsOpenApiGenerationException("OpenAPI document does not contain any supported path operations."); var source = EmitSource(version, sourceName, root, models, operations); return new XpsOpenApiGenerationResult(version, source, operations.Select(operation => operation.Name).ToArray(), models.Keys.OrderBy(name => name, StringComparer.OrdinalIgnoreCase).ToArray()); }
    private static Dictionary<string, JsonObject> SelectReferencedModels(JsonObject root, XpsOpenApiModelCatalog catalog, IReadOnlySet<string> included)
    {
        var selected = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (root["paths"] is JsonObject paths)
            foreach (var path in paths)
                if (path.Value is JsonObject item)
                    foreach (var method in HttpMethods)
                        if (item[method] is JsonObject operation && (included.Contains(path.Key) || included.Contains(method.ToUpperInvariant() + " " + path.Key) || (operation["operationId"] is JsonValue id && id.TryGetValue<string>(out var name) && included.Contains(name))))
                        {
                            CollectComponentReferences(root, operation, selected);
                        }
        var pending = new Queue<string>(selected);
        while (pending.Count > 0)
        {
            var wire = pending.Dequeue();
            if (root["components"]?["schemas"] is not JsonObject schemas || schemas[wire] is not JsonObject schema) continue;
            var before = selected.Count;
            CollectReferences(schema, selected);
            if (selected.Count != before) foreach (var name in selected) if (!pending.Contains(name)) pending.Enqueue(name);
        }
        return catalog.Models.Where(pair => selected.Contains(catalog.TypeNames.FirstOrDefault(type => type.Value.Equals(pair.Key, StringComparison.OrdinalIgnoreCase)).Key ?? pair.Key)).ToDictionary(pair => pair.Key, pair => pair.Value, StringComparer.OrdinalIgnoreCase);
    }
    private static void CollectReferences(JsonNode? node, HashSet<string> selected)
    {
        if (node is JsonObject obj)
        {
            if (obj["$ref"] is JsonValue value && value.TryGetValue<string>(out var reference)) { reference = reference.Trim().Trim('"'); if (reference.StartsWith("#/components/schemas/", StringComparison.Ordinal)) selected.Add(reference["#/components/schemas/".Length..]); }
            foreach (var child in obj.Select(pair => pair.Value)) CollectReferences(child, selected);
        }
        else if (node is JsonArray array) foreach (var child in array) CollectReferences(child, selected);
    }
    private static void CollectComponentReferences(JsonObject root, JsonNode? node, HashSet<string> selected)
    {
        if (node is JsonObject obj)
        {
            if (obj["$ref"] is JsonValue value && value.TryGetValue<string>(out var reference))
            {
                reference = reference.Trim().Trim('"');
                if (!reference.StartsWith("#/components/", StringComparison.Ordinal)) goto SkipComponentReference;
                var parts = reference["#/components/".Length..].Split('/', 2);
                if (parts.Length == 2 && parts[0].Equals("schemas", StringComparison.OrdinalIgnoreCase)) selected.Add(parts[1]);
                else if (parts.Length == 2 && root["components"]?[parts[0]]?[parts[1]] is JsonNode component) CollectComponentReferences(root, component, selected);
            }
            SkipComponentReference:;
            foreach (var child in obj.Select(pair => pair.Value)) CollectComponentReferences(root, child, selected);
        }
        else if (node is JsonArray array) foreach (var child in array) CollectComponentReferences(root, child, selected);
    }
    private static JsonObject ParseDocument(string specification, string? sourceName) { try { var trimmed = specification.AsSpan().TrimStart(); if (!trimmed.IsEmpty && (trimmed[0] == '{' || trimmed[0] == '[')) return JsonNode.Parse(specification) as JsonObject ?? throw new XpsOpenApiGenerationException("OpenAPI JSON root must be an object."); var stream = new YamlStream(); stream.Load(new StringReader(specification)); if (stream.Documents.Count != 1) throw new XpsOpenApiGenerationException("OpenAPI YAML must contain exactly one document."); return ConvertYamlNode(stream.Documents[0].RootNode) as JsonObject ?? throw new XpsOpenApiGenerationException("OpenAPI YAML root must be a mapping/object."); } catch (XpsOpenApiGenerationException) { throw; } catch (Exception ex) when (ex is JsonException or YamlException or FormatException) { throw new XpsOpenApiGenerationException($"Unable to parse OpenAPI specification{FormatSourceName(sourceName)} at {(ex is YamlException yaml ? $"line {yaml.Start.Line}, column {yaml.Start.Column}: " : string.Empty)}{ex.Message}", ex); } }
    private static bool IsSelectedOperation(string generatedName, string requestedName) => generatedName.Equals(requestedName, StringComparison.OrdinalIgnoreCase) || (generatedName.StartsWith(requestedName, StringComparison.OrdinalIgnoreCase) && int.TryParse(generatedName[requestedName.Length..], out _));
    private static JsonNode? ConvertYamlNode(YamlNode node) { switch (node) { case YamlMappingNode mapping: { var result = new JsonObject(); foreach (var entry in mapping.Children) { if (entry.Key is not YamlScalarNode key || string.IsNullOrWhiteSpace(key.Value)) throw new XpsOpenApiGenerationException("OpenAPI YAML mapping keys must be non-empty scalar strings."); if (result.ContainsKey(key.Value)) throw new XpsOpenApiGenerationException($"OpenAPI YAML contains duplicate key '{key.Value}'."); result[key.Value] = ConvertYamlNode(entry.Value); } return result; } case YamlSequenceNode sequence: { var result = new JsonArray(); foreach (var child in sequence.Children) result.Add(ConvertYamlNode(child)); return result; } case YamlScalarNode scalar: return ConvertYamlScalar(scalar); default: throw new XpsOpenApiGenerationException($"Unsupported YAML node type '{node.NodeType}'."); } }
    private static JsonNode? ConvertYamlScalar(YamlScalarNode scalar) { var value = scalar.Value ?? string.Empty; if (scalar.Style is ScalarStyle.SingleQuoted or ScalarStyle.DoubleQuoted or ScalarStyle.Literal or ScalarStyle.Folded) return JsonValue.Create(value); if (value is "~" || value.Equals("null", StringComparison.OrdinalIgnoreCase)) return null; if (bool.TryParse(value, out var boolean)) return JsonValue.Create(boolean); if (long.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var integer)) return JsonValue.Create(integer); if (double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var number)) return JsonValue.Create(number); return JsonValue.Create(value); }
    private static XpsOpenApiModelCatalog CollectComponentModels(JsonObject root)
        => XpsOpenApiModelCatalog.Collect(root, (rawName, used) =>
        {
            var name = ToSchemaIdentifier(rawName, $"schema '{rawName}'");
            if (!used.Add(name))
                throw new XpsOpenApiGenerationException($"OpenAPI schemas generate duplicate XPScript class name '{name}'.");
            return name;
        });
    private static List<OperationModel> CollectOperations(JsonObject root, Dictionary<string, JsonObject> models) { if (root["paths"] is not JsonObject paths) throw new XpsOpenApiGenerationException("OpenAPI document is missing the required 'paths' object."); var operations = new List<OperationModel>(); var usedNames = new HashSet<string>(models.Keys, StringComparer.OrdinalIgnoreCase); foreach (var modelName in models.Keys.Where(name => name.EndsWith("Response", StringComparison.OrdinalIgnoreCase))) usedNames.Add(modelName[..^8]); foreach (var modelName in models.Keys.Where(name => name.EndsWith("Request", StringComparison.OrdinalIgnoreCase))) usedNames.Add(modelName[..^7]); var rootSecurity = root["security"]; ValidateSecuritySchemes(root); foreach (var pathPair in paths) { if (pathPair.Value is not JsonObject pathItem) continue; var pathParameters = ReadParameters(root, pathItem["parameters"], $"paths.{pathPair.Key}.parameters"); foreach (var method in HttpMethods) { if (pathItem[method] is not JsonObject operation) continue; var rawName = ReadString(operation, "operationId") ?? BuildOperationName(method, pathPair.Key); var name = UniqueOperationName(ToTypeIdentifier(rawName, $"operation '{method.ToUpperInvariant()} {pathPair.Key}'"), usedNames); var parameters = MergeParameters(pathParameters, ReadParameters(root, operation["parameters"], $"{method.ToUpperInvariant()} {pathPair.Key} parameters")); EnsureUniqueParameters(parameters, method, pathPair.Key); var body = ReadRequestBody(root, operation["requestBody"], name, models, $"{method.ToUpperInvariant()} {pathPair.Key} requestBody"); var responses = ReadResponses(root, operation["responses"], $"{method.ToUpperInvariant()} {pathPair.Key} responses"); var security = operation.ContainsKey("security") ? operation["security"] : rootSecurity; var authenticated = ReadServerSecurity(root, security, $"{method.ToUpperInvariant()} {pathPair.Key} security"); operations.Add(new OperationModel(method.ToUpperInvariant(), pathPair.Key, name, parameters, body, responses, authenticated)); } } return operations; }
    private static void ValidateSecuritySchemes(JsonObject root) { if (root["components"] is not JsonObject components || components["securitySchemes"] is not JsonObject schemes) return; foreach (var pair in schemes) { if (pair.Value is not JsonObject scheme) throw new XpsOpenApiGenerationException($"components.securitySchemes.{pair.Key} must be an object."); var type = ReadString(scheme, "type")?.ToLowerInvariant() ?? throw new XpsOpenApiGenerationException($"Security scheme '{pair.Key}' is missing 'type'."); if (type is not ("apikey" or "http" or "oauth2" or "openidconnect" or "mutualtls")) throw new XpsOpenApiGenerationException($"Security scheme '{pair.Key}' uses unsupported type '{type}'."); } }
    private static bool ReadServerSecurity(JsonObject root, JsonNode? node, string context) { if (node is null) return false; if (node is not JsonArray requirements) throw new XpsOpenApiGenerationException($"{context} must be an array."); if (requirements.Count == 0) return false; if (root["components"] is not JsonObject components || components["securitySchemes"] is not JsonObject schemes) throw new XpsOpenApiGenerationException($"{context} references security but components.securitySchemes is missing."); var allowsAnonymous = false; foreach (var requirementNode in requirements) { if (requirementNode is not JsonObject requirement) throw new XpsOpenApiGenerationException($"{context} contains a security requirement that is not an object."); if (requirement.Count == 0) { allowsAnonymous = true; continue; } foreach (var pair in requirement) { if (!schemes.ContainsKey(pair.Key)) throw new XpsOpenApiGenerationException($"{context} references undefined security scheme '{pair.Key}'."); if (pair.Value is not JsonArray) throw new XpsOpenApiGenerationException($"{context} scheme '{pair.Key}' must declare an array of scopes."); } } return !allowsAnonymous; }
    private static List<ParameterModel> ReadParameters(JsonObject root, JsonNode? node, string context) { var result = new List<ParameterModel>(); if (node is null) return result; if (node is not JsonArray array) throw new XpsOpenApiGenerationException($"{context} must be an array."); foreach (var entry in array) { var parameter = XpsOpenApiSchema.Resolve(root, entry, context); var name = ReadString(parameter, "name") ?? throw new XpsOpenApiGenerationException($"{context} contains a parameter without a name."); var location = ReadString(parameter, "in")?.ToLowerInvariant() ?? throw new XpsOpenApiGenerationException($"Parameter '{name}' in {context} is missing 'in'."); if (location == "path" && !ReadBoolean(parameter, "required")) throw new XpsOpenApiGenerationException($"Path parameter '{name}' in {context} must declare required: true."); if (location is not ("path" or "query" or "header" or "cookie")) throw new XpsOpenApiGenerationException($"Parameter '{name}' uses unsupported location '{location}'. Supported locations are path, query, header and cookie."); if (parameter["schema"] is not JsonObject schema) throw new XpsOpenApiGenerationException($"Parameter '{name}' in {context} must declare a schema."); var typeName = XpsOpenApiSchema.XpsType(root, schema, $"parameter '{name}'"); result.Add(new ParameterModel(name, location, typeName, IsReferenceAssignmentType(typeName), ReadBoolean(parameter, "required"))); } return result; }
    private static List<ParameterModel> MergeParameters(IReadOnlyList<ParameterModel> inherited, IReadOnlyList<ParameterModel> operation) { var result = new List<ParameterModel>(inherited); foreach (var parameter in operation) { var index = result.FindIndex(existing => existing.Name.Equals(parameter.Name, StringComparison.Ordinal) && existing.Location.Equals(parameter.Location, StringComparison.OrdinalIgnoreCase)); if (index >= 0) result[index] = parameter; else result.Add(parameter); } return result; }
    private static RequestBodyModel? ReadRequestBody(JsonObject root, JsonNode? node, string operationName, Dictionary<string, JsonObject> models, string context) { if (node is null) return null; var requestBody = XpsOpenApiSchema.Resolve(root, node, context); if (requestBody["content"] is not JsonObject content) throw new XpsOpenApiGenerationException($"{context} must declare content."); var media = SelectRequestMediaType(content, context); if (media["schema"] is not JsonObject schema) return new RequestBodyModel("XPJsonObject", true, ReadBoolean(requestBody, "required"), new JsonObject()); if (XpsOpenApiSchema.TryGetReference(schema, out var reference)) { var resolved = XpsOpenApiSchema.Resolve(root, schema, context); var typeName = XpsOpenApiSchema.XpsType(root, schema, context); return new RequestBodyModel(typeName, IsReferenceAssignmentType(typeName), ReadBoolean(requestBody, "required"), resolved); } var type = XpsOpenApiSchema.PrimaryType(schema); if (type == "object" || schema.ContainsKey("properties")) { var modelName = UniqueModelName(operationName + "Body", models.Keys); models.Add(modelName, schema); return new RequestBodyModel(modelName, true, ReadBoolean(requestBody, "required"), schema); } var scalarTypeName = XpsOpenApiSchema.XpsType(root, schema, context); return new RequestBodyModel(scalarTypeName, IsReferenceAssignmentType(scalarTypeName), ReadBoolean(requestBody, "required"), schema); }
    private static List<ResponseModel> ReadResponses(JsonObject root, JsonNode? node, string context) { var result = new List<ResponseModel>(); if (node is not JsonObject responses) throw new XpsOpenApiGenerationException($"{context} must be an object and contain at least one response."); foreach (var pair in responses) { if (!pair.Key.Equals("default", StringComparison.OrdinalIgnoreCase) && (!int.TryParse(pair.Key, NumberStyles.None, CultureInfo.InvariantCulture, out var status) || status is < 100 or > 599)) throw new XpsOpenApiGenerationException($"Response key '{pair.Key}' in {context} is not a valid HTTP status code or 'default'."); var response = XpsOpenApiSchema.Resolve(root, pair.Value, $"{context}.{pair.Key}"); string? dataType = null; if (response["content"] is JsonObject content) { var jsonMedia = TrySelectJsonMediaType(content); if (jsonMedia?["schema"] is JsonObject schema) dataType = DescribeSchemaType(root, schema, $"{context}.{pair.Key}"); } result.Add(new ResponseModel(pair.Key, dataType)); } if (result.Count == 0) throw new XpsOpenApiGenerationException($"{context} must contain at least one response."); return result; }
    private static string EmitSource(string version, string? sourceName, JsonObject root, Dictionary<string, JsonObject> models, IReadOnlyList<OperationModel> operations) { var builder = new StringBuilder(); builder.AppendLine("Option Declare"); builder.AppendLine(); builder.AppendLine($"' Generated by XPScript from OpenAPI {version}{(string.IsNullOrWhiteSpace(sourceName) ? string.Empty : " - " + sourceName)}"); builder.AppendLine("' Handler functions are safe extension points. Regeneration overwrites this file."); builder.AppendLine(); foreach (var model in models.OrderBy(pair => pair.Key, StringComparer.OrdinalIgnoreCase)) { EmitModel(builder, root, model.Key, model.Value); builder.AppendLine(); } foreach (var operation in operations) { EmitOperation(builder, operation); builder.AppendLine(); } return builder.ToString().TrimEnd() + Environment.NewLine; }
    private static void EmitModel(StringBuilder builder, JsonObject root, string name, JsonObject schema) { var resolved = XpsOpenApiSchema.Resolve(root, schema, $"schema '{name}'"); builder.AppendLine($"Public Class {name}"); if (resolved["properties"] is not JsonObject properties || properties.Count == 0) { builder.AppendLine("    Public Value As Variant"); builder.AppendLine("End Class"); return; } var required = ReadStringSet(resolved["required"]); var usedFieldNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { name }; foreach (var property in properties) { var fieldName = ModelMemberName(property.Key, name, usedFieldNames); if (property.Value is not JsonObject propertySchema) throw new XpsOpenApiGenerationException($"Schema '{name}' property '{property.Key}' must be an object."); var fieldType = XpsOpenApiSchema.XpsType(root, propertySchema, $"schema '{name}' property '{property.Key}'"); if (!fieldName.Equals(property.Key, StringComparison.Ordinal)) builder.AppendLine($"    ' OpenAPI property: {property.Key}"); if (required.Contains(property.Key)) builder.AppendLine("    [Required]"); var resolvedProperty = XpsOpenApiSchema.Resolve(root, propertySchema, $"schema '{name}' property '{property.Key}'"); if (ReadString(resolvedProperty, "format")?.Equals("email", StringComparison.OrdinalIgnoreCase) == true) builder.AppendLine("    [Email]"); if (TryReadInt(resolvedProperty, "maxLength", out var maxLength) && maxLength is > 0 and <= 1000000) builder.AppendLine($"    [MaxLength:{maxLength.ToString(CultureInfo.InvariantCulture)}]"); if (TryReadRangeNumber(resolvedProperty, "minimum", out var minimum) && TryReadRangeNumber(resolvedProperty, "maximum", out var maximum) && minimum.Value <= maximum.Value) builder.AppendLine($"    [Range:{minimum.Text};{maximum.Text}]"); builder.AppendLine($"    Public {fieldName} As {fieldType}"); builder.AppendLine(); } if (builder.Length >= Environment.NewLine.Length * 2) builder.Length -= Environment.NewLine.Length; builder.AppendLine("End Class"); }
    private static void EmitOperation(StringBuilder builder, OperationModel operation) { var requestClass = operation.Name + "Request"; var responseClass = operation.Name + "Response"; var endpointName = "Endpoint" + operation.Name; var fields = BuildRequestFields(operation); builder.AppendLine($"Public Class {requestClass}"); if (fields.Count == 0) builder.AppendLine("    Public HasInput As Boolean"); else foreach (var field in fields) builder.AppendLine($"    Public {field.FieldName} As {field.TypeName}"); builder.AppendLine("End Class"); builder.AppendLine(); builder.AppendLine($"Public Class {responseClass}"); builder.AppendLine("    Public StatusCode As Integer"); builder.AppendLine("    Public Data As Variant"); builder.AppendLine("End Class"); builder.AppendLine(); builder.AppendLine($"' OpenAPI responses: {string.Join(", ", operation.Responses.Select(FormatResponseDescription))}"); builder.AppendLine($"Function Handle{operation.Name}(request As {requestClass}) As {responseClass}"); builder.AppendLine($"    Dim result As {responseClass}"); builder.AppendLine($"    Set result = New {responseClass}"); builder.AppendLine("    ' TODO: implement this operation and set result.StatusCode/result.Data."); builder.AppendLine("    result.StatusCode = 501"); builder.AppendLine($"    Set Handle{operation.Name} = result"); builder.AppendLine("End Function"); builder.AppendLine(); builder.AppendLine(operation.Authenticated ? "[Authenticated]" : "[Anonymous]"); builder.AppendLine($"[{ToHttpAttribute(operation.Method)}]"); builder.AppendLine($"[Route:{operation.Path}]"); var parameters = BuildWrapperParameters(operation); builder.AppendLine($"Sub {endpointName}({string.Join(", ", parameters.Select(parameter => parameter.Declaration))})"); builder.AppendLine($"    Dim request As {requestClass}"); builder.AppendLine($"    Set request = New {requestClass}"); builder.AppendLine($"    Dim result As {responseClass}"); foreach (var parameter in parameters) builder.AppendLine($"    {(parameter.IsObject ? "Set " : string.Empty)}request.{parameter.FieldName} = {parameter.VariableName}"); builder.AppendLine($"    Set result = Handle{operation.Name}(request)"); builder.AppendLine($"    Call Write{operation.Name}Response(result)"); builder.AppendLine("End Sub"); builder.AppendLine(); builder.AppendLine($"Sub Write{operation.Name}Response(result As {responseClass})"); builder.AppendLine("    If result.StatusCode = 204 Then"); builder.AppendLine("        Response.NoContent()"); builder.AppendLine("    Else"); builder.AppendLine("        Response.Json(result.StatusCode, result.Data)"); builder.AppendLine("    End If"); builder.AppendLine("End Sub"); }
    private static List<RequestField> BuildRequestFields(OperationModel operation) { var fields = new List<RequestField>(); var used = new HashSet<string>(StringComparer.OrdinalIgnoreCase); foreach (var parameter in operation.Parameters) { var baseName = ToTypeIdentifier(parameter.Name, $"parameter '{parameter.Name}'"); var fieldName = UniqueFieldName(baseName, parameter.Location, used); fields.Add(new RequestField(fieldName, parameter.TypeName, parameter.IsObject, parameter)); } if (operation.Body is not null) { var fieldName = UniqueFieldName("Payload", "body", used); fields.Add(new RequestField(fieldName, operation.Body.TypeName, operation.Body.IsObject, operation.Body)); } return fields; }
    private static List<WrapperParameter> BuildWrapperParameters(OperationModel operation) { var fields = BuildRequestFields(operation); var result = new List<WrapperParameter>(); foreach (var field in fields) { if (field.Source is ParameterModel parameter) { var variableName = "p" + field.FieldName; var binding = parameter.Location switch { "path" => "FromRoute", "query" => "FromQuery", "header" => "FromHeader", "cookie" => "FromCookie", _ => throw new InvalidOperationException("Unsupported parameter location.") }; var escapedName = parameter.Name.Replace("\"", "\"\"", StringComparison.Ordinal); result.Add(new WrapperParameter(field.FieldName, variableName, field.TypeName, field.IsObject, $"[{binding}:\"{escapedName}\"] {variableName} As {field.TypeName}")); } else { const string variableName = "payload"; result.Add(new WrapperParameter(field.FieldName, variableName, field.TypeName, field.IsObject, $"[FromBody] {variableName} As {field.TypeName}")); } } return result; }
    private static JsonObject SelectRequestMediaType(JsonObject content, string context) { var json = TrySelectJsonMediaType(content); if (json is not null) return json; foreach (var pair in content) if (pair.Value is JsonObject media && media["schema"] is JsonObject) return media; throw new XpsOpenApiGenerationException($"{context} must contain at least one media type with a schema."); }
    private static JsonObject? TrySelectJsonMediaType(JsonObject content) { if (content["application/json"] is JsonObject exact) return exact; foreach (var pair in content) if (pair.Key.EndsWith("+json", StringComparison.OrdinalIgnoreCase) && pair.Value is JsonObject media) return media; foreach (var wildcard in new[] { "application/*", "*/*" }) if (content[wildcard] is JsonObject media && media["schema"] is JsonObject) return media; return null; }
    private static string DescribeSchemaType(JsonObject root, JsonObject schema, string context) { if (XpsOpenApiSchema.TryGetReference(schema, out var reference)) return XpsOpenApiSchema.ReferenceTypeName(reference, context); return XpsOpenApiSchema.XpsType(root, schema, context); }
    private static void EnsureUniqueParameters(IReadOnlyList<ParameterModel> parameters, string method, string path) { var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase); foreach (var parameter in parameters) if (!seen.Add(parameter.Location + "\0" + parameter.Name)) throw new XpsOpenApiGenerationException($"{method.ToUpperInvariant()} {path} declares duplicate {parameter.Location} parameter '{parameter.Name}'."); }
    private static HashSet<string> ReadStringSet(JsonNode? node) { var result = new HashSet<string>(StringComparer.Ordinal); if (node is not JsonArray array) return result; foreach (var item in array) if (item is JsonValue value && value.TryGetValue<string>(out var text)) result.Add(text); return result; }
    private static string ModelMemberName(string name, string modelName, HashSet<string> used) { if (string.IsNullOrWhiteSpace(name)) throw new XpsOpenApiGenerationException($"Schema '{modelName}' declares an empty property name."); var baseName = IdentifierPattern.IsMatch(name) && !IsDeclarationReserved(name) ? name : ToTypeIdentifier(name, $"schema '{modelName}' property '{name}'"); var candidate = baseName; var suffix = 2; while (!used.Add(candidate)) candidate = baseName + suffix++.ToString(CultureInfo.InvariantCulture); return candidate; }
    private static string ToSchemaIdentifier(string value, string context) { if (string.IsNullOrWhiteSpace(value)) throw new XpsOpenApiGenerationException($"{context} has an empty identifier."); var trimmed = value.Trim(); return IdentifierPattern.IsMatch(trimmed) && !IsDeclarationReserved(trimmed) ? trimmed : ToTypeIdentifier(trimmed, context); }
    private static string ToTypeIdentifier(string value, string context) { if (string.IsNullOrWhiteSpace(value)) throw new XpsOpenApiGenerationException($"{context} has an empty identifier."); var parts = Regex.Split(value.Trim(), "[^A-Za-z0-9_]+", RegexOptions.CultureInvariant).Where(part => part.Length > 0).ToArray(); if (parts.Length == 0) throw new XpsOpenApiGenerationException($"{context} cannot be converted to an XPScript identifier."); var joined = string.Concat(parts.Select(Pascalize)); if (joined.Length == 0 || char.IsDigit(joined[0])) joined = "Api" + joined; if (!IdentifierPattern.IsMatch(joined)) throw new XpsOpenApiGenerationException($"{context} cannot be converted to an XPScript identifier."); if (IsDeclarationReserved(joined)) joined = "Api" + joined; return joined; }
    private static bool IsDeclarationReserved(string identifier) => identifier.StartsWith("__", StringComparison.OrdinalIgnoreCase) || LexicalKeywords.Contains(identifier) || identifier.Equals("Application", StringComparison.OrdinalIgnoreCase) || identifier.Equals("Body", StringComparison.OrdinalIgnoreCase) || identifier.Equals("Metadata", StringComparison.OrdinalIgnoreCase) || identifier.Equals("Program", StringComparison.OrdinalIgnoreCase) || identifier.Equals("Person", StringComparison.OrdinalIgnoreCase) || identifier.Equals("Request", StringComparison.OrdinalIgnoreCase) || identifier.Equals("Response", StringComparison.OrdinalIgnoreCase) || identifier.Equals("Platform", StringComparison.OrdinalIgnoreCase) || identifier.Equals("File", StringComparison.OrdinalIgnoreCase);
    private static string Pascalize(string value) => value.Length == 0 ? value : char.ToUpperInvariant(value[0]) + value[1..];
    private static string BuildOperationName(string method, string path) { var suffix = Regex.Replace(path, "[{}]", string.Empty, RegexOptions.CultureInvariant); return method + " " + suffix; }
    private static string UniqueOperationName(string name, HashSet<string> used) { if (used.Add(name)) return name; for (var suffix = 2; suffix < 10_000; suffix++) { var candidate = name + suffix.ToString(CultureInfo.InvariantCulture); if (used.Add(candidate)) return candidate; } throw new XpsOpenApiGenerationException($"Unable to generate a unique operation name for '{name}'."); }
    private static string UniqueModelName(string baseName, IEnumerable<string> existing) { var used = new HashSet<string>(existing, StringComparer.OrdinalIgnoreCase); if (!used.Contains(baseName)) return baseName; for (var suffix = 2; suffix < 10_000; suffix++) { var candidate = baseName + suffix.ToString(CultureInfo.InvariantCulture); if (!used.Contains(candidate)) return candidate; } throw new XpsOpenApiGenerationException($"Unable to generate a unique model name for '{baseName}'."); }
    private static string UniqueFieldName(string baseName, string location, HashSet<string> used) { if (used.Add(baseName)) return baseName; var prefixed = ToTypeIdentifier(location, "parameter location") + baseName; if (used.Add(prefixed)) return prefixed; for (var suffix = 2; suffix < 10_000; suffix++) { var candidate = prefixed + suffix.ToString(CultureInfo.InvariantCulture); if (used.Add(candidate)) return candidate; } throw new XpsOpenApiGenerationException($"Unable to generate a unique request field name for '{baseName}'."); }
    private static string ToHttpAttribute(string method) => method.Length == 0 ? method : char.ToUpperInvariant(method[0]) + method[1..].ToLowerInvariant();
    private static string FormatResponseDescription(ResponseModel response) => response.DataType is null ? response.StatusCode : response.StatusCode + " " + response.DataType;
    private static string? ReadString(JsonObject node, string propertyName) { if (node[propertyName] is JsonValue value && value.TryGetValue<string>(out var text)) return text; return null; }
    private static bool ReadBoolean(JsonObject node, string propertyName) => node[propertyName] is JsonValue value && value.TryGetValue<bool>(out var result) && result;
    private static bool TryReadInt(JsonObject node, string propertyName, out int result) { result = 0; if (node[propertyName] is not JsonValue value) return false; if (value.TryGetValue<int>(out result)) return true; if (value.TryGetValue<long>(out var longValue) && longValue is >= int.MinValue and <= int.MaxValue) { result = (int)longValue; return true; } return false; }
    private static bool TryReadRangeNumber(JsonObject node, string propertyName, out (decimal Value, string Text) result) { result = default; if (node[propertyName] is not JsonValue value) return false; if (value.TryGetValue<long>(out var integer)) { var number = (decimal)integer; result = (number, number.ToString(CultureInfo.InvariantCulture)); return true; } if (value.TryGetValue<double>(out var floatingPoint) && double.IsFinite(floatingPoint) && floatingPoint >= (double)decimal.MinValue && floatingPoint <= (double)decimal.MaxValue) { try { var number = (decimal)floatingPoint; result = (number, number.ToString(CultureInfo.InvariantCulture)); return true; } catch (OverflowException) { return false; } } return false; }
    private static bool IsReferenceAssignmentType(string typeName) => !typeName.Equals("XPJsonArray", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("XPJsonObject", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("Variant", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("String", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("Integer", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("Long", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("Single", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("Double", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("Boolean", StringComparison.OrdinalIgnoreCase) && !typeName.Equals("Date", StringComparison.OrdinalIgnoreCase);
    private static string FormatSourceName(string? sourceName) => string.IsNullOrWhiteSpace(sourceName) ? string.Empty : $" '{sourceName}'";
    private sealed record ParameterModel(string Name, string Location, string TypeName, bool IsObject, bool Required);
    private sealed record RequestBodyModel(string TypeName, bool IsObject, bool Required, JsonObject Schema);
    private sealed record ResponseModel(string StatusCode, string? DataType);
    private sealed record OperationModel(string Method, string Path, string Name, IReadOnlyList<ParameterModel> Parameters, RequestBodyModel? Body, IReadOnlyList<ResponseModel> Responses, bool Authenticated);
    private sealed record RequestField(string FieldName, string TypeName, bool IsObject, object Source);
    private sealed record WrapperParameter(string FieldName, string VariableName, string TypeName, bool IsObject, string Declaration);
}
