name: .NET 10 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Display .NET info
        run: dotnet --info

      - name: Restore
        run: dotnet restore ./src/LSLite.Compiler/LSLite.Compiler.csproj

      - name: Build
        run: dotnet build ./src/LSLite.Compiler/LSLite.Compiler.csproj --configuration Release --no-restore
